# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


dob = Date.parse('1991-12-25')

lendee = Lendee.create([
  {first_name: 'Austin',
  last_name: 'Sprawls',
  email: 'asprawls@gmail.com',
  password: 'as759323',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 42000,
  credit_range: '660-720',
  },
  {first_name: 'Justin',
  last_name: 'Lilly',
  email: 'jlilly@gmail.com',
  password: 'jl759323',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 12000,
  credit_range: '600-660',
  },
  {first_name: 'Randy',
  last_name: 'Davis',
  email: 'rdavis@gmail.com',
  password: 'password',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 57800,
  credit_range: '720+',
  },
  {first_name: 'Aaron',
  last_name: 'Case',
  email: 'aacase@gmail.com',
  password: 'password',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 12000,
  credit_range: 'below 600',
  },
  {first_name: 'Daniel',
  last_name: 'Turner',
  email: 'dturner@gmail.com',
  password: 'jl759323',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 120000,
  credit_range: '720+',
  },
  {first_name: 'Catherine',
  last_name: 'Teacher',
  email: 'cteacher@gmail.com',
  password: 'password',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 12000,
  credit_range: '660-720',
  },
  {first_name: 'Emma',
  last_name: 'Follender',
  email: 'efollender@gmail.com',
  password: 'password',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 12000,
  credit_range: '600-660',
  },
  {first_name: 'Brian',
  last_name: 'Patterson',
  email: 'bpatterson@gmail.com',
  password: 'jl759323',
  street_address: '123 somewhere lane',
  city: 'Austin',
  state: 'TX',
  zip_code: '76841',
  date_of_birth: dob,
  yearly_individual_income: 12000,
  credit_range: '720+',
  }
])

lenders = Lender.create([
    {email: 'dcox@gmail.com',
    password: 'dc9082102',
    state_of_residence: 'TX'},
    {email: 'jbeuck@gmail.com',
    password: 'password',
    state_of_residence: 'TX'},
    {email: 'joe@gmail.com',
    password: 'password',
    state_of_residence: 'TX'},
    {email: 'pgauthier@gmail.com',
    password: 'password',
    state_of_residence: 'TX'},
    {email: 'quinlan@gmail.com',
    password: 'password',
    state_of_residence: 'TX'},
    {email: 'dellis@gmail.com',
    password: 'password',
    state_of_residence: 'TX'},
    {email: 'chris@gmail.com',
    password: 'password',
    state_of_residence: 'TX'},
    {email: 'wchen@gmail.com',
    password: 'password',
    state_of_residence: 'TX'}
])

expiration = Date.parse('2015-01-06')

loans = Loan.create([
  {lendee_id: lendee.first.id,
  amount: 7000,
  expiration_date: expiration,
  rate: 7.71,
  term: 60
  },
  {lendee_id: lendee[1].id,
   amount: 10000,
   expiration_date: expiration,
   rate: 17.98,
   term: 36
   },
   {lendee_id: lendee[2].id,
    amount: 14567,
    expiration_date: expiration,
    rate: 7.71,
    term: 36
   },
   {lendee_id: lendee[3].id,
    amount: 11020,
    expiration_date: expiration,
    rate: 24.63,
    term: 36
   },
   {lendee_id: lendee[4].id,
    amount: 10000,
    expiration_date: expiration,
    rate: 7.71,
    term: 60
  },
  {lendee_id: lendee[5].id,
   amount: 9865,
   expiration_date: expiration,
   rate: 12.99,
   term: 60
   },
   {lendee_id: lendee[6].id,
    amount: 10000,
    expiration_date: expiration,
    rate: 17.98,
    term: 36
   },
   {lendee_id: lendee[7].id,
    amount: 13478,
    expiration_date: expiration,
    rate: 7.71,
    term: 36
    }

])

# investments = Investment.create([
#   {lender_id: lenders.first.id,
#   loan_id: loans.first.id,
#   amount: 2000},
#   {lender_id: lenders.first.id,
#   loan_id: loans.first.id,
#   amount: 5000}
# ])
